### ISSUE TITLE
Unable to resolve service for type 'NewLife.Log.ITracer' while attempting to activate 'NewLife.Cube.Services.JobService'.

### ISSUE THREAD

**Issue by SmallShrimp** [NewLifeX/AntJob#6]
允许***AntJob.Web***的时候
13:49:13.066  1 N - NewLife.Core v8.10.2021.0427-beta1 Build 2021-04-27 21:26:50 .NETCoreApp,Version=v5.0
13:49:13.080  1 N - X组件核心库 ?2002-2021 NewLife
13:49:13.080  1 N - AntWeb v2.2.2021.0103 Build 2021-05-05 11:18:22 .NETCoreApp,Version=v5.0
13:49:13.081  1 N - 蚂蚁调度控制台 版权所有(C) 新生命开发团队 2021
13:49:13.081  1 N - ================================ Start 配置魔方 ================================
13:49:13.082  1 N - NewLife.Cube v3.9.2021.0427-beta3 Build 2021-04-27 22:44:22 .NETCoreApp,Version=v5.0
13:49:13.082  1 N - 魔方平台 ?2002-2021 NewLife
13:49:13.145  1 N - XCode v10.1.2021.0427-beta3 Build 2021-04-27 21:26:56 .NETCoreApp,Version=v5.0
13:49:13.146  1 N - 数据中间件 ?2002-2021 NewLife
13:49:13.618  1 N - 注册区域视图程序集：NewLife.Cube, Version=3.9.7787.40931, Culture=neutral, PublicKeyToken=null
13:49:13.619  1 N - 注册区域视图程序集：NewLife.Cube.Views, Version=3.9.7787.40932, Culture=neutral, PublicKeyToken=null
13:49:13.619  1 N - 注册区域视图程序集：AntWeb.Views, Version=2.2.7795.20352, Culture=neutral, PublicKeyToken=null
13:49:13.619  1 N - 注册区域视图程序集：AntWeb, Version=2.2.7795.20351, Culture=neutral, PublicKeyToken=null
13:49:13.620  1 N - ================================ End   配置魔方 ================================
13:49:13.680  1 N - System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: NewLife.Cube.Services.JobService': Unable to resolve service for type 'NewLife.Log.ITracer' while attempting to activate 'NewLife.Cube.Services.JobService'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: NewLife.Cube.Services.JobService': Unable to resolve service for type 'NewLife.Log.ITracer' while attempting to activate 'NewLife.Cube.Services.JobService'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'NewLife.Log.ITracer' while attempting to activate 'NewLife.Cube.Services.JobService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at AntJob.Web.Program.Main(String[] args) in D:\gitee\AntJob\AntJob.Web\Program.cs:line 15
13:49:13.684  1 N - 异常退出！

**Comment by nnhy** [comment]
这个问题源自于魔方，为了增加Cron定时任务，JobService要求注入ITracer，而普通web应用使用魔方后并没有注入ITracer，导致启动报错。这个问题已经修正，今晚发布魔方正式版。

**Comment by SmallShrimp** [comment]
你好，已经解决了吗，今天更新了代码 还是同样的错误呢

**Comment by SmallShrimp** [comment]
更新了nuget 现在可以了

**Comment by nnhy** [comment]
网络问题，代码实在推不上去
